"""Write local previews and safely refresh only previously generated files."""

from __future__ import annotations

import hashlib
from html import escape
import json
from pathlib import Path
import re

from .errors import ReportError
from .models import Report
from .rendering import brl, render_html, render_text


def write_previews(reports: list[Report], output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True, mode=0o700)
    manifest = output / "manifest.json"
    if manifest.exists():
        try:
            previous = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ReportError("Manifesto das prévias inválido; use outra output_dir ou remova o manifesto.") from exc
        if not isinstance(previous, list):
            raise ReportError("Manifesto das prévias deve ser uma lista.")
        for filename in previous:
            # Only remove files previously generated by this script in this folder.
            if not isinstance(filename, str) or not re.fullmatch(r"[a-zA-Z0-9_-]+-[a-f0-9]{8}\.(html|txt)", filename):
                raise ReportError("Nome inválido no manifesto das prévias.")
            (output / filename).unlink(missing_ok=True)
    files, links = [], []
    for report in reports:
        slug = re.sub(r"[^a-zA-Z0-9_-]", "_", report.recipient.sheet)
        suffix = hashlib.sha256(report.recipient.sheet.encode()).hexdigest()[:8]
        stem = f"{slug}-{suffix}"
        for extension, content in (("html", render_html(report)), ("txt", render_text(report))):
            filename = f"{stem}.{extension}"
            (output / filename).write_text(content, encoding="utf-8")
            files.append(filename)
        links.append(f'<li><a href="{stem}.html">{escape(report.recipient.sheet)}</a> — saldo {escape(brl(report.balance))}</li>')
    (output / "index.html").write_text(
        '<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Prévias dos cartões</title>'
        '<body style="font-family:Calibri,Arial,sans-serif;padding:20px"><h1>Prévias dos resumos</h1>'
        '<p>Nenhum e-mail foi enviado.</p><ul>' + ''.join(links) + '</ul></body></html>', encoding="utf-8")
    manifest.write_text(json.dumps(files, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
