"""Byte-for-byte rendering contracts captured before the package extraction.

All names, contacts and purchases here are synthetic. The committed golden file
is deliberately not regenerated by tests: changes require explicit review.
"""
from dataclasses import replace
from datetime import date
from decimal import Decimal
import json
from pathlib import Path
import unittest

from resumos_cartoes import rendering
from resumos_cartoes.models import Purchase, Recipient, Report


def example_reports():
    base = Report(
        "black", "2026-09", Recipient("Pessoa01", "Participante01", "person@example.com"),
        (
            Purchase(date(2025, 1, 3), "Loja <teste> & detalhes", "10 de 12", Decimal("2000.00"), Decimal("1000.01")),
            Purchase(date(2026, 9, 1), "Estorno", "—", Decimal("-2.35"), Decimal("-2.35")),
        ),
        (Decimal("-5.65"), Decimal("-2.00")),
        "Titular <fictício>", "Pagamento: referência & teste",
    )
    return {
        "debt": base,
        "settled": replace(base, card="latam", payments=(Decimal("-997.66"),), payment_footer=None),
        "credit": replace(base, purchases=(), payments=(Decimal("-7.65"),)),
        "empty": replace(base, purchases=(), payments=(), owner_name=None, payment_footer=None),
    }


class RenderingCharacterizationTests(unittest.TestCase):
    def test_complete_html_text_subject_and_totals_match_original(self):
        expected = json.loads((Path(__file__).parent / "fixtures/golden_reports.json").read_text(encoding="utf-8"))
        self.assertEqual(set(expected), set(example_reports()))
        for name, report in example_reports().items():
            with self.subTest(name=name):
                self.assertEqual(rendering.render_html(report), expected[name]["html"])
                self.assertEqual(rendering.render_text(report), expected[name]["text"])
                self.assertEqual(rendering.subject(report), expected[name]["subject"])
                self.assertEqual(str(report.spending), expected[name]["spending"])
                self.assertEqual(str(report.balance), expected[name]["balance"])
                self.assertEqual(report.has_movement, expected[name]["has_movement"])


if __name__ == "__main__":
    unittest.main()
